apiVersion: v1

kind: Pod
metadata:
  name: sshwordle
spec:
    containers:
    - name: sshwordle
      imagePullPolicy: Always
      image: ghcr.io/davidcroda/sshwordle:main
      workingDir: /app
      ports:
      - containerPort: 1337
        hostIP: 0.0.0.0
        hostPort: 1337
